package tests;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.openqa.selenium.*;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import java.net.URL;


public class SeleniumTest {

    private static final String CLOUD_ACCESS_KEY = System.getenv("CLOUD_ACCESS_KEY");
    private static final String VISUAL_ACCESS_KEY = System.getenv("VISUAL_ACCESS_KEY");
    private WebDriver driver;
    private URL url;
    private DesiredCapabilities dc = new DesiredCapabilities();

    @Parameters({"browser_name", "browser_version"})
    @BeforeMethod
    public void setUp(String browser_name, String browser_version) throws Exception {
        url = new URL("https://sales.experitest.com:443/wd/hub");
        dc.setCapability(CapabilityType.BROWSER_NAME, browser_name);
        dc.setCapability(CapabilityType.VERSION, browser_version);
        dc.setCapability(CapabilityType.PLATFORM, Platform.XP);
        dc.setCapability("accessKey", CLOUD_ACCESS_KEY);
        dc.setCapability("testName", "Travis Visual Testing Demo");
        dc.setCapability("seleniumScreenshot", true);
        driver = new RemoteWebDriver(url, dc);
    }


    @Test
    public void testExperitest() {
        driver.get("https://www.google.com/");
        new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfElementLocated(By.id("lst-ib")));
        WebElement search_field = driver.findElement(By.id("lst-ib"));
        search_field.sendKeys("github login");
        search_field.sendKeys(Keys.RETURN);
        new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"rso\"]/div[1]/div/div/div/div/h3/a")));
        WebElement first_result = driver.findElement(By.xpath("//*[@id=\"rso\"]/div[1]/div/div/div/div/h3/a"));
        first_result.click();
        new WebDriverWait(driver, 10).until(ExpectedConditions.presenceOfElementLocated(By.id("login_field")));
        in.Visual.setAccessKey(VISUAL_ACCESS_KEY);
        boolean result  = in.Visual.verify(driver, "github_login_page");
        System.out.println("Report Link: " + in.Visual.getLastResultUrl());
    }

    @AfterMethod
    public void tearDown() {
        driver.quit();
    }

}